#!/bin/bash
set -Eeuo pipefail
trap 'echo "❌ Chroot stage failed at line $LINENO"' ERR

USERNAME="$(ls -1 /home | head -n1)"
HOME_DIR="/home/$USERNAME"

if [[ -z "$USERNAME" ]] || ! id "$USERNAME" &>/dev/null; then
  echo "❌ Could not determine valid user"
  exit 1
fi
exec > >(tee -a /var/log/lishalinux-install.log) 2>&1

echo "=== LishaLinux chroot staging ==="

# 1. TEMP passwordless sudo (removed on first boot)
echo "Setting temp passwordless sudo..."
echo "$USERNAME ALL=(ALL) NOPASSWD: ALL" >/etc/sudoers.d/temp-lishalinux-setup
chmod 440 /etc/sudoers.d/temp-lishalinux-setup

# 2. Autologin via getty (disable SDDM)
echo "Configuring getty autologin..."
systemctl disable sddm || true

mkdir -p /etc/systemd/system/getty@tty1.service.d
cat >/etc/systemd/system/getty@tty1.service.d/autologin.conf <<EOF
[Service]
ExecStart=
ExecStart=-/sbin/agetty -a $USERNAME --noclear %I \$TERM
Environment=XDG_SESSION_TYPE=wayland
EOF

# 3. Staging directory (NOT ~/.config)
echo "Creating staging directory..."
mkdir -p "$HOME_DIR/lishalinux-setup"
chown -R $USERNAME:$USERNAME "$HOME_DIR/lishalinux-setup"

# 4. DROP FIRST-BOOT SCRIPT (RUNS AFTER REAL BOOT)
cat >"$HOME_DIR/lishalinux-setup/first-boot.sh" <<'EOF'
#!/bin/bash
# LishaLinux First Boot — Hyprland-based (NO systemd user services)

set -e

# Prevent re-run
[ -f "$HOME/.lishalinux-installed" ] && exit 0

# Wait for Wayland
while [ -z "$WAYLAND_DISPLAY" ]; do
    sleep 1
done

# Hyprland config edits (clean screen FIRST)
mkdir -p "$HOME/.config/hypr"

cat >>"$HOME/.config/hypr/hyprland.conf" <<'HYPR'

monitor=,preferred,auto,auto

$terminal = kitty

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

general {
    gaps_in = 5
    gaps_out = 20

    border_size = 2

    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 10
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 1.0
    inactive_opacity = 1.0

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

$mainMod = SUPER # Sets "Windows" key as main modifier

bind = $mainMod, T, exec, $terminal
bind = $mainMod, Q, killactive,

# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}


autogenerated = 0
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_watchdog_warning = true
}

windowrule = float on, match:tag floating-window
windowrule = center on, match:tag floating-window
windowrule = size 875 600, match:tag floating-window
windowrule = tag +floating-window, match:class org.lishalinux.terminal

HYPR

# Launch installer terminal

kitty \
  --config NONE \
  --override font_family="CaskaydiaMono Nerd Font" \
  --override font_size=10.0 \
  --override foreground=#cdd6f4 \
  --override background=#1e1e2e \
  --override color2=#a6e3a1 \
  --override color10=#a6e3a1 \
  --override selection_foreground=#1e1e2e \
  --override selection_background=#89b4fa \
  --override window_padding_width=15 \
  --app-id=org.lishalinux.terminal \
  --title="Lishalinux" \
  -e bash -c '
clear

printf "\033[32m%s\033[0m\n\n" "
 ▄█             ▄█          ▄████████         ▄█    █▄            ▄████████ 
███            ███         ███    ███        ███    ███          ███    ███ 
███            ███▌        ███    █▀         ███    ███          ███    ███ 
███            ███▌        ███              ▄███▄▄▄▄███▄▄        ███    ███ 
███            ███▌      ▀███████████      ▀▀███▀▀▀▀███▀       ▀███████████ 
███            ███                ███        ███    ███          ███    ███ 
███▌    ▄      ███          ▄█    ███        ███    ███          ███    ███ 
█████▄▄██      █▀         ▄████████▀         ███    █▀           ███    █▀  
"

rows=$(tput lines)
printf "\e[11;${rows}r"
printf "\e[11;1H"

rm -rf "$HOME/lishalinux"
git clone https://github.com/rawalrauf/lishalinux
chmod +x lishalinux/install.sh
./lishalinux/install.sh

printf "\e[r"
printf "\e[999;1H"
echo ""

gum spin --spinner globe --title "Done! Press any key to close..." -- bash -c "read -n 1 -s"
'

# CLEANUP (runs AFTER installer finishes)

touch "$HOME/.lishalinux-installed"

rm -f "$HOME/.lishalinux-autostart"

sudo systemctl enable sddm
sudo rm -f /etc/systemd/system/getty@tty1.service.d/autologin.conf
sudo rmdir /etc/systemd/system/getty@tty1.service.d 2>/dev/null || true

sudo rm -f /etc/sudoers.d/temp-lishalinux-setup

sleep 3
reboot
EOF

chmod +x "$HOME_DIR/lishalinux-setup/first-boot.sh"
chown $USERNAME:$USERNAME "$HOME_DIR/lishalinux-setup/first-boot.sh"

# 5. Hyprland autostart hook (TTY → Hyprland)
cat >"$HOME_DIR/.lishalinux-autostart" <<'EOF'
if [ -z "$WAYLAND_DISPLAY" ] && [ "$XDG_VTNR" -eq 1 ]; then
    exec Hyprland
fi
EOF

chown $USERNAME:$USERNAME "$HOME_DIR/.lishalinux-autostart"

# 6. Ensure hook is sourced
grep -q lishalinux-autostart "$HOME_DIR/.bash_profile" 2>/dev/null ||
  echo '[ -f ~/.lishalinux-autostart ] && source ~/.lishalinux-autostart' \
    >>"$HOME_DIR/.bash_profile"

# 7. Hook first boot into Hyprland exec-once
mkdir -p "$HOME_DIR/.config/hypr"
touch "$HOME_DIR/.config/hypr/hyprland.conf"

grep -q first-boot.sh "$HOME_DIR/.config/hypr/hyprland.conf" ||
  echo "exec-once = $HOME_DIR/lishalinux-setup/first-boot.sh" \
    >>"$HOME_DIR/.config/hypr/hyprland.conf"

chown -R $USERNAME:$USERNAME "$HOME_DIR/.config"
echo "Chroot went well"
